import { readdir, writeFile } from 'node:fs/promises';
import { extname, join, relative } from 'node:path';

const root = process.cwd();
const publicRoot = join(root, 'public');
const output = join(root, 'src', 'generated', 'image-assets.ts');
const supported = new Set(['.jpeg', '.jpg', '.png']);

async function walk(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const path = join(directory, entry.name);
      return entry.isDirectory() ? walk(path) : [path];
    })
  );
  return files.flat();
}

const images = (await walk(publicRoot))
  .filter((path) => supported.has(extname(path).toLowerCase()))
  .map((path) => `/${relative(publicRoot, path).replaceAll('\\\\', '/')}`)
  .sort();

const declarations = images.map((path, index) => {
  const source = `../../public${path}`;
  return `  ${JSON.stringify(path)}: image(new URL(${JSON.stringify(source)}, import.meta.url))${
    index === images.length - 1 ? '' : ','
  }`;
});

const source = `// Generated by scripts/generate-image-assets.ts. Do not edit.\nimport { image, type ResponsiveImage } from '@askrjs/vite/image';\n\nexport const imageAssets: Readonly<Record<string, ResponsiveImage>> = {\n${declarations.join('\n')}\n};\n`;

await writeFile(output, source);
console.log(`Generated ${images.length} responsive image declarations.`);
